#Please keep this configuration file
server:
  port: 8080

spring:
  application:
    name: web

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration



#pagehelper:
#  support-methods-arguments: true
#  params: pageNum=page;pageSize=perPage
#mybatis:
#  configuration:
#    return-instance-for-empty-row: true
